[[Libgpg_error]]
arch = "aarch64"
git-tree-sha1 = "b396c237827e57728b15a221c45469a1c73c5a18"
os = "macos"

    [[Libgpg_error.download]]
    sha256 = "19ad0ac9df6cafe5ff2ffd250027029b9f4c5a825741e423839890817c7df55d"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.59.0+0/Libgpg_error.v1.59.0.aarch64-apple-darwin.tar.gz"
[[Libgpg_error]]
arch = "aarch64"
git-tree-sha1 = "23d8a239cc2ca708c65625c5bb2564635e149cb3"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "fc162ba4c00e130ca70496ac0b3945b12d08216096caae9202332bb7dab4d1eb"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.59.0+0/Libgpg_error.v1.59.0.aarch64-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "aarch64"
git-tree-sha1 = "877a420a2623374ea3d5cb730c4a8e657ea74b5c"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "c57c254554b7f5d4fbbbed497ffb258cf3dc5724e4a0523a1208711dd99c32d6"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.59.0+0/Libgpg_error.v1.59.0.aarch64-linux-musl.tar.gz"
[[Libgpg_error]]
arch = "aarch64"
git-tree-sha1 = "152b7a10005eb66936963eec650e0d327e047e85"
os = "freebsd"

    [[Libgpg_error.download]]
    sha256 = "c8305684f18a57eeab9a24e7f29baa74f7f2d1ffa1d33a3af58a4a4733903ecf"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.59.0+0/Libgpg_error.v1.59.0.aarch64-unknown-freebsd.tar.gz"
[[Libgpg_error]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0c06e69bf70155a73cf6bc582678e1a979adc29b"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "2a7b8f32ae9423ac4be7fab0569a8e0b8b23dfdad0b4a7e2b86e42b00c63ca2e"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.59.0+0/Libgpg_error.v1.59.0.armv6l-linux-gnueabihf.tar.gz"
[[Libgpg_error]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "187d49c7e69d998625e57c5feebccda203b18e69"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "22620afa720ebc314379994ae74ed053b43292624dbf14e13a2f4229256aec2a"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.59.0+0/Libgpg_error.v1.59.0.armv6l-linux-musleabihf.tar.gz"
[[Libgpg_error]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b27e454210fd90edff7e111b9980c248cc0ceca5"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "c4321ffed5c05671957f8fb8766d25de98b90bda35c40e737b0d751717f85017"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.59.0+0/Libgpg_error.v1.59.0.armv7l-linux-gnueabihf.tar.gz"
[[Libgpg_error]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "16fe736d79ca2d609eabeca2f65603233a0e836f"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "c09cfdd1cde968facc719b5ed26f86e33ae781b6104d9d683b4c3c213fdc4732"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.59.0+0/Libgpg_error.v1.59.0.armv7l-linux-musleabihf.tar.gz"
[[Libgpg_error]]
arch = "i686"
git-tree-sha1 = "f593a405cd0f381136395d0b2df987e6b7ef4eda"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "a6bea20c080a9fdc16b12f51427e787f9160bef151176a84f2982b0f3d9e2651"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.59.0+0/Libgpg_error.v1.59.0.i686-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "i686"
git-tree-sha1 = "2c037c6d35637e7a61974c6183062765af3f3669"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "9a85a95ffad7e0c2c8b86524b5a6d9a6e3faa77eaecc4f47795b55d5cdbc0984"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.59.0+0/Libgpg_error.v1.59.0.i686-linux-musl.tar.gz"
[[Libgpg_error]]
arch = "i686"
git-tree-sha1 = "b5d943a37adce596ae0e37884b34b244c425d45c"
os = "windows"

    [[Libgpg_error.download]]
    sha256 = "9196f94f4f5f4d2be9015107e341608a9f27a66484e706c894ce6b4eaf11c96b"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.59.0+0/Libgpg_error.v1.59.0.i686-w64-mingw32.tar.gz"
[[Libgpg_error]]
arch = "powerpc64le"
git-tree-sha1 = "0c68891567c318b322108a8fd257fec0e5199e74"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "a99626b6fd4e71b2e663ac5f94fd04156c18663881fedbde2bb82be021952518"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.59.0+0/Libgpg_error.v1.59.0.powerpc64le-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "riscv64"
git-tree-sha1 = "d57d3a199c11daa7bfdad7d3090dcece749280be"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "a930795daff6e1a4ac1bc6948c93628e12e961dace674649f666a2eb64ebd219"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.59.0+0/Libgpg_error.v1.59.0.riscv64-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "e6317a6aa4ef86c0daaf3c8bfe1e889428201480"
os = "macos"

    [[Libgpg_error.download]]
    sha256 = "605cef3bf7fedd7d5605282926dc4fca28885159dbacf02cbe3521d716ab33e1"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.59.0+0/Libgpg_error.v1.59.0.x86_64-apple-darwin.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "7eca693d674caa13a439c06a9da49a6ca59ddca7"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "d226c97af13a0695f44659c7919a930a53ac5e0e4b69b9f335fe4957f1cfbeb3"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.59.0+0/Libgpg_error.v1.59.0.x86_64-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "8bff79225412ad1fa6a819e2ae5d69203a40a521"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "0dc546f8799e515fdfca86427222272c0322610bf8ff3c3c94545b1f180fecd0"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.59.0+0/Libgpg_error.v1.59.0.x86_64-linux-musl.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "c54c332cfa47691755a210a1bdda4337c6d1cdf1"
os = "freebsd"

    [[Libgpg_error.download]]
    sha256 = "9d74eb2643f8f8a45427d21059a8bcb1f049d894a97bf136de1acc4e27bd4102"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.59.0+0/Libgpg_error.v1.59.0.x86_64-unknown-freebsd.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "0f078cfbfdd8d8b88aa293c6df8faeccf58d99ab"
os = "windows"

    [[Libgpg_error.download]]
    sha256 = "11ac68dadf31e359866efa577309b5d4fe6e2267984dce79c30eecd878d7426a"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.59.0+0/Libgpg_error.v1.59.0.x86_64-w64-mingw32.tar.gz"
