[[Libgpg_error]]
arch = "aarch64"
git-tree-sha1 = "9788987d61ff78cbec2f46327eeb10658b54c1aa"
os = "macos"

    [[Libgpg_error.download]]
    sha256 = "f6535d3fc3b57f08b6f662755cff833fa74ff29eddb08ee0cd3f335467883948"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.58.0+0/Libgpg_error.v1.58.0.aarch64-apple-darwin.tar.gz"
[[Libgpg_error]]
arch = "aarch64"
git-tree-sha1 = "243ee4649611af64b7e48ef3c2daa6f545f0ad9c"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "847bf60b11e35a032dabf5b2c3bc978cc46f519a9c4d9617eda509aecb83bb78"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.58.0+0/Libgpg_error.v1.58.0.aarch64-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "aarch64"
git-tree-sha1 = "b73b06b771f343c9b4f6f706363916a921a82ebb"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "8f8ee144e3fabe949a9b92402f56f743ac499bdfbbf7cbd0dd46016bc3db6477"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.58.0+0/Libgpg_error.v1.58.0.aarch64-linux-musl.tar.gz"
[[Libgpg_error]]
arch = "aarch64"
git-tree-sha1 = "d799d4c1347ea43b08285a72e66875a44de6e839"
os = "freebsd"

    [[Libgpg_error.download]]
    sha256 = "cf1d1ccc22c5c4716a8039a41ecec3072998b4b8d8fba60a7f6795f028d7613f"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.58.0+0/Libgpg_error.v1.58.0.aarch64-unknown-freebsd.tar.gz"
[[Libgpg_error]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f8592dbdbed62a9cab06f19892c9ffb00a0d409e"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "b82093fe3e7e633e24e850b1278fc74c5a4b3e4afc60d986bccec2346241908e"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.58.0+0/Libgpg_error.v1.58.0.armv6l-linux-gnueabihf.tar.gz"
[[Libgpg_error]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "207903343552563f7a72d7001e89778385944311"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "630dd17354aedf0fe7092a8746baffe7566689181e14ae058165d46cbb27ed11"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.58.0+0/Libgpg_error.v1.58.0.armv6l-linux-musleabihf.tar.gz"
[[Libgpg_error]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "973cad8f52dd5a3e277fc7df44497130e2e800f2"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "3412bcbfa9ee151637f7dc7e96e5329402d854343d187fc12598b662c2293713"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.58.0+0/Libgpg_error.v1.58.0.armv7l-linux-gnueabihf.tar.gz"
[[Libgpg_error]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "db32b468785bbbb760ee325dc4918090610f26fe"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "e2cbee99bb349ceaab39b5dc07f9392e0079ed9319dec1fd4b1d50fafa19ecde"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.58.0+0/Libgpg_error.v1.58.0.armv7l-linux-musleabihf.tar.gz"
[[Libgpg_error]]
arch = "i686"
git-tree-sha1 = "8d0f691fef6f780ed0f0a35fa95d0503db2c3517"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "b2f05c39123dfc03de98dcfc9a097f91ae73dfb0738b51aa23573a78590931c7"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.58.0+0/Libgpg_error.v1.58.0.i686-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "i686"
git-tree-sha1 = "aa4a53f8975f9b41f9202db41b40f25101a2eb06"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "84fa518dd457b9380bd7ac7d6a527543aabeaf38db6114cd54bced68f896f2f3"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.58.0+0/Libgpg_error.v1.58.0.i686-linux-musl.tar.gz"
[[Libgpg_error]]
arch = "i686"
git-tree-sha1 = "a25b4db12b1e868f58cdf35b6c23f0fe4d4d2a5d"
os = "windows"

    [[Libgpg_error.download]]
    sha256 = "64493d72aba158fbdf48b04cf5df2e8eae3f7e63af1618fdaaa68a07bd50778e"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.58.0+0/Libgpg_error.v1.58.0.i686-w64-mingw32.tar.gz"
[[Libgpg_error]]
arch = "powerpc64le"
git-tree-sha1 = "2ba96d1a3179bfb57232604d9651fe6e3269ef9c"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "d74b34a766c29186b21f2cdc50d4818691b05fa5d0eb262e6c89f3aac5ca3bd4"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.58.0+0/Libgpg_error.v1.58.0.powerpc64le-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "riscv64"
git-tree-sha1 = "25990c30e1750e83fcf8347943c6ceb3ef0462d7"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "3ac245ec5ba5665fb75d1dff46360fa9e5e671bc2624bf7c3bbc98c816c539d2"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.58.0+0/Libgpg_error.v1.58.0.riscv64-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "d6aa741de949183d906c7bd9166243a62d97a817"
os = "macos"

    [[Libgpg_error.download]]
    sha256 = "093a7c31dbc33bec1e8c5523cf884d463b8c4a8c6a4be37dd3bba196c009f9cb"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.58.0+0/Libgpg_error.v1.58.0.x86_64-apple-darwin.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "e189ccba8149d3f7a4bf850cd15eb0fa5a2d4964"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "36f78b78eab08d630962685fd992ba8a68b9a429e04e845b479bafe13ae6f470"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.58.0+0/Libgpg_error.v1.58.0.x86_64-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "a51e1e1807e3fa2344a01d7f70db039fad48745f"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "168330d202c05f50b3452b414a7ed27d24f92825fad040608637cc4934ab2120"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.58.0+0/Libgpg_error.v1.58.0.x86_64-linux-musl.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "1e303a49a65358b4549d1e426764dac898fa4834"
os = "freebsd"

    [[Libgpg_error.download]]
    sha256 = "6a0e82708c85b0971b4edb158a19aac0809a2cddce50226ef3b694b47dfacf9c"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.58.0+0/Libgpg_error.v1.58.0.x86_64-unknown-freebsd.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "b654e15add078435437ea93105303511aaff81b7"
os = "windows"

    [[Libgpg_error.download]]
    sha256 = "14af851574b881bd62316816f63c072a10eec4767d942a2227610e1196b02a15"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.58.0+0/Libgpg_error.v1.58.0.x86_64-w64-mingw32.tar.gz"
