[[Libgpg_error]]
arch = "aarch64"
git-tree-sha1 = "900e7d0917e56f81e6b10f8aac767c08a21ac17f"
os = "macos"

    [[Libgpg_error.download]]
    sha256 = "f64e7e9736be148cb277130967d283e08bdf6e7cfed8af730da5e34114b094fb"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.50.0+0/Libgpg_error.v1.50.0.aarch64-apple-darwin.tar.gz"
[[Libgpg_error]]
arch = "aarch64"
git-tree-sha1 = "0d55fdab778927dee2021baf21763c7b63dba8f7"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "8aa9f58abc7b6468d74bd107a9365c01cdb746d6d61966704b6994d5d16adea8"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.50.0+0/Libgpg_error.v1.50.0.aarch64-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "aarch64"
git-tree-sha1 = "f83f9e4321effd25757ce036eab55acb3ec597de"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "46bf60c8ff5e46b069676bb3229226d0426c479bd4d97bf5b35563bec0a06603"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.50.0+0/Libgpg_error.v1.50.0.aarch64-linux-musl.tar.gz"
[[Libgpg_error]]
arch = "aarch64"
git-tree-sha1 = "a63db501b90b94f7a01ea00f811baf778c8fc727"
os = "freebsd"

    [[Libgpg_error.download]]
    sha256 = "a4fa04bbaa7418b01c4808867c15396fb89a7805f9150562f4383417fd9d9710"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.50.0+0/Libgpg_error.v1.50.0.aarch64-unknown-freebsd.tar.gz"
[[Libgpg_error]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0db49833a58dde95c51a35088aadd55101d7cd1a"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "9d9e3e4d64da9ce11a8786ddbf5ee5a33476af3fe18949734c6b0e02fda77f98"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.50.0+0/Libgpg_error.v1.50.0.armv6l-linux-gnueabihf.tar.gz"
[[Libgpg_error]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "27867e3de39472a32d5f99c7fed2e48279123079"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "59c07fb3174b0000532257bfc45aff27ecfc3f802137618cef19dbe53b9341e3"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.50.0+0/Libgpg_error.v1.50.0.armv6l-linux-musleabihf.tar.gz"
[[Libgpg_error]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab903e91496e7ea8a6ed7827de879178856ba955"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "11c2d67c7e9b6fdc8b14f3ff5ef85e25a43d8b03bc0006b093b3bb4e5c7dac87"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.50.0+0/Libgpg_error.v1.50.0.armv7l-linux-gnueabihf.tar.gz"
[[Libgpg_error]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4ce2d75e6e3bd948512013bfb13657d51a564255"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "120a0dbd12f4419e70b329d402d001bf347523165043ac0cbfddc4828ee8a030"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.50.0+0/Libgpg_error.v1.50.0.armv7l-linux-musleabihf.tar.gz"
[[Libgpg_error]]
arch = "i686"
git-tree-sha1 = "ed12accbef12d594e7274f0801f2c3b4f8cd652e"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "598f4d08ba93bc1ecb14740ca6084a005e179005ee484011088245abde0b0bd6"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.50.0+0/Libgpg_error.v1.50.0.i686-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "i686"
git-tree-sha1 = "21bd2a52ae2b7a32e1cc090ed82845f4e3f880ac"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "f48ab970f59bc540a58192ec35b26e21d13e5aad3bc50f9a1629ab81a094a6a9"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.50.0+0/Libgpg_error.v1.50.0.i686-linux-musl.tar.gz"
[[Libgpg_error]]
arch = "i686"
git-tree-sha1 = "8428f03b0e8f1206a6ce90d7c92ce54c3f4a7652"
os = "windows"

    [[Libgpg_error.download]]
    sha256 = "e9bc362874b6fdbf79ea18aaa3e825202bce312bd4ada4390ac12d2cc7d51e0e"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.50.0+0/Libgpg_error.v1.50.0.i686-w64-mingw32.tar.gz"
[[Libgpg_error]]
arch = "powerpc64le"
git-tree-sha1 = "62ea2caadfff404fc23ed0a1497e5981d413694d"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "69a422d4f7d844db7ffcb79faec5105930ad3ec21b1ba21cdf5ed93141db31da"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.50.0+0/Libgpg_error.v1.50.0.powerpc64le-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "5102c071627daa00a338fbd4cbe7bfd4df6d9b94"
os = "macos"

    [[Libgpg_error.download]]
    sha256 = "563bddd7873f3527a0bedacbf2495abd2031a54f3d7dcc28759cc477d4689e0c"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.50.0+0/Libgpg_error.v1.50.0.x86_64-apple-darwin.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "d75cfbd8954fdbc933ebead40a9c8b91513c023a"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "0115b10dacdfb4b3f414ead79c4e7cb6fbe59ca18d1152656414b88d827197f4"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.50.0+0/Libgpg_error.v1.50.0.x86_64-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "ed8cbb7f2619bd849833f40a301a11cfe3c4ec86"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "bd33a4be69ff566cd0c1e2d01dce81f2fd8bfd5de15139de7f634d115b0862a5"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.50.0+0/Libgpg_error.v1.50.0.x86_64-linux-musl.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "385f8289d9f0b04073f676418e5361299aa45eb1"
os = "freebsd"

    [[Libgpg_error.download]]
    sha256 = "be63bd5745aec03e1bdd3383b56a70d0aad81017ab956e85a90e0167c138bc1b"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.50.0+0/Libgpg_error.v1.50.0.x86_64-unknown-freebsd.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "c2c562e569ec0c6ac0700fa3fdc1cf3163e7fc0d"
os = "windows"

    [[Libgpg_error.download]]
    sha256 = "9bf89aa199c96ecb2e79b0c511fa0e2a68d12123373d8f0df4cde42979772784"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.50.0+0/Libgpg_error.v1.50.0.x86_64-w64-mingw32.tar.gz"
