[[Libgpg_error]]
arch = "aarch64"
git-tree-sha1 = "63730740b2e7d3a65e14422bd5b7f065d1453719"
os = "macos"

    [[Libgpg_error.download]]
    sha256 = "b56dcc7a2834be8ec2c3cdad6db9318b3f24744d8f1051a3e1e4aaa68aa6037d"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.57.0+0/Libgpg_error.v1.57.0.aarch64-apple-darwin.tar.gz"
[[Libgpg_error]]
arch = "aarch64"
git-tree-sha1 = "866f5ea263cad11965a67d1c3e1b59646c884bb2"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "659ad35a486687fce7c3b97a758e937dfb59230945ad8e19d97da21cc116016e"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.57.0+0/Libgpg_error.v1.57.0.aarch64-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "aarch64"
git-tree-sha1 = "ea5f6f0845832bbfaf8aac2943d0b42cc530ddfe"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "8f23ca6a7e89fd0c4195457f4d09f5753dddc77b9b8add3c8eb212996e953615"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.57.0+0/Libgpg_error.v1.57.0.aarch64-linux-musl.tar.gz"
[[Libgpg_error]]
arch = "aarch64"
git-tree-sha1 = "6291eb3ee9fa0112cdb0816b708d05dfb88403e8"
os = "freebsd"

    [[Libgpg_error.download]]
    sha256 = "e59d3d1a5d55eb935faf53630cefa4ba74b2646fb0bd1411b0ddae46beb6cf26"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.57.0+0/Libgpg_error.v1.57.0.aarch64-unknown-freebsd.tar.gz"
[[Libgpg_error]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d4b0214d4f094208fd38a7ddd3b96f80fd8c7466"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "dcb59e355368b59ced482ee2601bec9671a2ed760cc48796b7d63f03b21c6f11"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.57.0+0/Libgpg_error.v1.57.0.armv6l-linux-gnueabihf.tar.gz"
[[Libgpg_error]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1299f48966bbcf7f0465d29aaceab36b928107b9"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "68aa54ab104ed754b480dac4759e08daef64cec39e1e953c7b569e1e4611c93a"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.57.0+0/Libgpg_error.v1.57.0.armv6l-linux-musleabihf.tar.gz"
[[Libgpg_error]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fc1840be8d1d2e1bad7db236a0f1231101308251"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "18b5df4b2a886644936138bf18bf9ee4b75a09d4b8966ad789cf1f962a331b4b"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.57.0+0/Libgpg_error.v1.57.0.armv7l-linux-gnueabihf.tar.gz"
[[Libgpg_error]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9cfcaf246ec18e02b8b9c44858485ce8dc3eef3a"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "129729fc01e78b957e99c7f31dfc33e73cebd940c90107483fc0c376e03beb47"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.57.0+0/Libgpg_error.v1.57.0.armv7l-linux-musleabihf.tar.gz"
[[Libgpg_error]]
arch = "i686"
git-tree-sha1 = "eee4a6e4ad1b9bd8cc77db31641020fa99d53a81"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "2f1e574f3543d97a37bbc9eb49e9acaca99da06912966f106142ba076c7476ec"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.57.0+0/Libgpg_error.v1.57.0.i686-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "i686"
git-tree-sha1 = "a819e303ceac662bd946fbe1472e7ec43b075213"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "4baa903339b2e87ba9da0f864fa14132c05a5e8aa2c2eff416f1d495de3c52ce"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.57.0+0/Libgpg_error.v1.57.0.i686-linux-musl.tar.gz"
[[Libgpg_error]]
arch = "i686"
git-tree-sha1 = "de9cc3f6bdea8b619f8ce3ac6ef0cbb7b8855298"
os = "windows"

    [[Libgpg_error.download]]
    sha256 = "0bdd3d91a6e9c33876b63377d31819089d109662bcf19fccf0f7ec01f5203066"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.57.0+0/Libgpg_error.v1.57.0.i686-w64-mingw32.tar.gz"
[[Libgpg_error]]
arch = "powerpc64le"
git-tree-sha1 = "c5dff2504ed64b95f2b3b6b34de2e390fd2e8d0e"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "51aebf6d76ac9d1b9e9c992bc892d892bfd7208fad447cb7c2bf4700b9a9748d"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.57.0+0/Libgpg_error.v1.57.0.powerpc64le-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "riscv64"
git-tree-sha1 = "0850eb5d57f61bf539369865e2b3403b22c1e62f"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "494cf2586882c2e96d77623f81a3d8c32bd97eaae3caccf3f1cedfeb0e8708f8"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.57.0+0/Libgpg_error.v1.57.0.riscv64-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "28cafd9ac63da5581b31875bdaf606e19fd0fed6"
os = "macos"

    [[Libgpg_error.download]]
    sha256 = "be62cce7c7a4e103e6e6589c21c83d5ef6f2ecbb79b76db7021bc61ec81d7aeb"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.57.0+0/Libgpg_error.v1.57.0.x86_64-apple-darwin.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "6dceb7102fd063a39180cee2d8eb66b09e853cdf"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "6de0b741637963a0b58b6bd3a1b215db2bfae95bd9fc1eed354b4f6d4af12db8"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.57.0+0/Libgpg_error.v1.57.0.x86_64-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "b438db842d874551e75088b4f9198e9e189022bf"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "49c5fc162a25541f716df28793e08e29eecb18304ea94e513579c98f11a467a4"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.57.0+0/Libgpg_error.v1.57.0.x86_64-linux-musl.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "507bb9ad69759f3c6f639c445b711bfebd13e1b4"
os = "freebsd"

    [[Libgpg_error.download]]
    sha256 = "adc1977d0e8f92d2f333379966ab1dfd1f281b6002321bc9db1a349669bc3e2a"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.57.0+0/Libgpg_error.v1.57.0.x86_64-unknown-freebsd.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "051fbfcf95974cc480d8e5d1ee052aabfcd4b1ef"
os = "windows"

    [[Libgpg_error.download]]
    sha256 = "4d1fbc989b435c069e0417280b6ad6b4e726001ffe8b01a540c0084cec0c9045"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.57.0+0/Libgpg_error.v1.57.0.x86_64-w64-mingw32.tar.gz"
