[[Libgpg_error]]
arch = "i686"
git-tree-sha1 = "7c0c22c9e85229742829028129528f885b196941"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "f567d21897fd9a38a3508779458e71e5417284909b02f494f6363908a6e4fa53"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.36.0+1/Libgpg_error.v1.36.0.i686-linux-musl.tar.gz"
[[Libgpg_error]]
arch = "aarch64"
git-tree-sha1 = "00cd33b1826e4f253af4dd8604faf5ed149912d2"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "4f1bbda4c39b068a503e0c8f5dc62c405a41d46baa0bfc1f46d96febeeb603ef"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.36.0+1/Libgpg_error.v1.36.0.aarch64-linux-musl.tar.gz"
[[Libgpg_error]]
arch = "i686"
git-tree-sha1 = "2023b4c2d2a9d8961b9f64cc0ff6bcbf32fd746c"
os = "windows"

    [[Libgpg_error.download]]
    sha256 = "4daa497b0aa3ce4a0675e6ebe832869042a30a901b87b176f7c9a081a719567c"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.36.0+1/Libgpg_error.v1.36.0.i686-w64-mingw32.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "68e651c223741117e02471f9e5611ac0421eef82"
os = "windows"

    [[Libgpg_error.download]]
    sha256 = "09ffaf033fd45f47255ed5d1402813f0174af7d2b2c242542de2a8e0d14b9416"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.36.0+1/Libgpg_error.v1.36.0.x86_64-w64-mingw32.tar.gz"
[[Libgpg_error]]
arch = "armv7l"
git-tree-sha1 = "ad430b276170074b3054ffb2c916595663ef68c7"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "ee0f5d2bc35746fbc82509948ad7aaa5958572015ae6d3ee57836c66eeb1d4ce"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.36.0+1/Libgpg_error.v1.36.0.armv7l-linux-gnueabihf.tar.gz"
[[Libgpg_error]]
arch = "armv7l"
git-tree-sha1 = "d7475d4f85bd9c03f789f66329b12be1e4a6a09c"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "3ab8c2962c962ea2cebd2ad2ce6f1d6b6d2cb461537f81a4f247605f71a43ac2"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.36.0+1/Libgpg_error.v1.36.0.armv7l-linux-musleabihf.tar.gz"
[[Libgpg_error]]
arch = "i686"
git-tree-sha1 = "2b305295649a8ad6cca3f2926bde4b55cc13e498"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "f86bbeb52889958093e7baea9de13925836f4a3b32444946ebd293eb099c9651"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.36.0+1/Libgpg_error.v1.36.0.i686-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "e19c90e613b33bb590dba7dc05dab746838a1fad"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "8068712545c76aa27fb51b07dc0f550da2a4e7b66c86a2fa9498d9fb28c00d34"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.36.0+1/Libgpg_error.v1.36.0.x86_64-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "powerpc64le"
git-tree-sha1 = "9ff3901c50c3722279ec344304bce609f942040b"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "79a5638c5b2cce9f2ad4616af4f5b6606037d445823d69697e1f78fc45532420"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.36.0+1/Libgpg_error.v1.36.0.powerpc64le-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "4a7aa43474d3fc05356c0939f30de59165534069"
os = "macos"

    [[Libgpg_error.download]]
    sha256 = "7a016d1153f44bf69e974d07110ff2d1665d65fc211886659067892a1b45159c"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.36.0+1/Libgpg_error.v1.36.0.x86_64-apple-darwin14.tar.gz"
[[Libgpg_error]]
arch = "aarch64"
git-tree-sha1 = "e5e826462d8cb9b58e7ceb23336e04d42e9cea7a"
libc = "glibc"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "21614b43c3f4b944e84992f9b584e9ae42ed7062cd5fe094dd6c45e0e7fffa93"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.36.0+1/Libgpg_error.v1.36.0.aarch64-linux-gnu.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "d928c53c4d3b09b248dc52bb1c5237ed7d99a67c"
os = "freebsd"

    [[Libgpg_error.download]]
    sha256 = "0bad50e4388d8f73ae67cf77953c67f075497c83d08c52aafb262c3e6c37778c"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.36.0+1/Libgpg_error.v1.36.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Libgpg_error]]
arch = "x86_64"
git-tree-sha1 = "10c3717ff7ee2e44b61847decf970c6d254d9411"
libc = "musl"
os = "linux"

    [[Libgpg_error.download]]
    sha256 = "bbf866ade7a323d88a888c2e6a6cefc889dd32c48c73be31a6711fd4b2461202"
    url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.36.0+1/Libgpg_error.v1.36.0.x86_64-linux-musl.tar.gz"
